### ISSUE TITLE
Update 2021, Komodod for notary has commit from june 2020

### ISSUE THREAD

**Issue by imylomylo** [KomodoPlatform/Documentation#102]
mylo_SH — Today at 1:02 PM

https://docs.komodoplatform.com/notary/setup-Komodo-Notary-Node.html#clone-the-source-checkout-master-branch-and-compile

:point_up_2: heads up

the commit in this doc is from jun 2020 https://github.com/KomodoPlatform/komodo/tree/e159b4e

**Comment by gcharang** [comment]
thanks! this doc is only ever used at the season start and it is only relevant to the elected notaries. and, then each update is an incremental change with an update doc announced to the OPs. I think we should cleanup+update this doc before the start of next season and doing so before that isn't necessary.
