### ISSUE TITLE
Update LRC token address

### ISSUE THREAD

**Issue by dong77** [KomodoPlatform/Documentation#13]
LRC's address has changed from 0xEF68e7C694F40c8202821eDF525dE3782458639f to 0xEF68e7C694F40c8202821eDF525dE3782458639f (lrctoken.eth)

More details: https://medium.com/loopring-protocol/lrc-token-upgraded-a26ee6f87b84

**Comment by gcharang** [comment]
Hello!

If this is about correcting details for the DEX, please open the issue here: https://github.com/jl777/coins . Better yet, open a pull request. Instructions: https://github.com/jl777/coins#5-ethereum-info-file-required-for-etherc20
